# Generated by Django 5.0.3 on 2024-04-03 14:11

import datetime
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='post date'),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('image_carousel', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('bullet_list', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock())), ('image_text', wagtail.blocks.StructBlock([('image1', wagtail.images.blocks.ImageChooserBlock()), ('caption1', wagtail.blocks.CharBlock()), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('caption2', wagtail.blocks.CharBlock())])), ('quote', wagtail.blocks.StructBlock([('quote_by', wagtail.blocks.CharBlock()), ('quotes', wagtail.blocks.RichTextBlock())]))], blank=True),
        ),
    ]
