# Generated by Django 5.0.3 on 2024-04-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_postpage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
