# Generated by Django 5.0.3 on 2024-04-06 10:58

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_postpage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('image_text', wagtail.blocks.StructBlock([('image1', wagtail.images.blocks.ImageChooserBlock()), ('caption1', wagtail.blocks.CharBlock()), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('caption2', wagtail.blocks.CharBlock())])), ('quote', wagtail.blocks.StructBlock([('quote_by', wagtail.blocks.CharBlock()), ('quotes', wagtail.blocks.RichTextBlock())]))], blank=True),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
