# Generated by Django 5.0.3 on 2024-04-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_postpage_body_alter_postpage_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='file',
            field=models.FileField(blank=True, upload_to='blog_files/'),
        ),
    ]
