# Generated by Django 5.0.3 on 2024-04-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_postpage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='header_image',
            field=models.ImageField(upload_to='blog_images/'),
        ),
    ]
